package tui

const (
	keyEnter             = "enter"
	keyEsc               = "esc"
	keySpace             = " "
	keyPlus              = "+"
	keyCtrlC             = "ctrl+c"
	keyCtrlF             = "ctrl+f"
	keyCtrlD             = "ctrl+d"
	keyCtrlB             = "ctrl+b"
	keyCtrlU             = "ctrl+u"
	keyCtrlH             = "ctrl+h"
	keyCtrlS             = "ctrl+s"
	keyPgDown            = "pgdown"
	keyPgUp              = "pgup"
	keyBackspace         = "backspace"
	keyBack              = "q"
	keyQuit              = "Q"
	keyCommand           = ":"
	keySearch            = "/"
	keyOpen              = "o"
	keyDelete            = "D"
	keyVimDown           = "j"
	keyVimUp             = "k"
	keyArrowDown         = "down"
	keyArrowUp           = "up"
	keyGoto              = "g"
	keyBottom            = "G"
	keyCites             = "c"
	keyCitedBy           = "b"
	keyReviewState       = "s"
	keySort              = "."
	keyColLeft           = "h"
	keyColRight          = "l"
	keyClassification    = "L"
	keyFullText          = "T"
	keyNotes             = "n"
	keyRefresh           = "ctrl+r"
	keyAI                = "a"
	keyWeb               = "w"
	keyJump              = "f"
	keyNarrow            = "#"
	keyVisual            = "v"
	keyVisualLine        = "V"
	keyVisualAll         = "%"
	keyFamily            = "F"
	keyProject           = "P"
	keyTag               = "t"
	keyCountry           = "C"
	keyFirstClaim        = "@"
	keyHelp              = "?"
	keyYes               = "y"
	keyNo                = "n"
	keyNew               = "n"
	keyIgnore            = "i"
	keyUnreview          = "r"
	keyRefreshAll        = "R"
	keyEvents            = "e"
	keyInvoices          = "i"
	keyIDS               = "I"
	keyMarkPaid          = "p"
	keyProjectInfo       = "i"
	keyAddToIDS          = "A"
	keyNoteEdit          = "N"
	keyEditAppStatus     = "s"
	keyEditSummary       = "m"
	keyEditComment       = "c"
	keyEditProjectStatus = "S"

	jumpFallbackLabels = "abcdefgimopqrstvwz"

	// Detail view field jump labels — pressed after [f] to jump to a specific field.
	// Fields that have both a key binding and a jump label use keySpec vars (below).
	jumpLabelAssignee         = "a"
	jumpLabelInventors        = "i"
	jumpLabelApplication      = "A"
	jumpLabelPublication      = "p"
	jumpLabelGrant            = "g"
	jumpLabelClassification   = "k"
	jumpLabelExpiration       = "x"
	jumpLabelFirstClaim       = "1"
	jumpLabelAbstract         = "m"
	jumpLabelStoredLocal      = "l"
	jumpLabelUpdated          = "u"
	jumpLabelSource           = "h"
	jumpLabelFamilyParents    = "P"
	jumpLabelFamilyChildren   = "C"
	jumpLabelLatestAssignment = "L"
	jumpLabelImportSource     = "v"
	jumpLabelCountry          = "o"

	inventorJumpNumberLabels = "123456789"
)
