package command

// viewCommands returns the viewCommands command registrations.
func viewCommands() []Command {
	return []Command{
		Command{ID: NavDown, Kind: KindView, Scopes: listScopes},
		Command{ID: NavUp, Kind: KindView, Scopes: listScopes},
		Command{ID: NavPageDown, Kind: KindView, Scopes: listScopes},
		Command{ID: NavPageUp, Kind: KindView, Scopes: listScopes},
		Command{ID: NavTop, Kind: KindView, Scopes: listScopes},
		Command{ID: NavBottom, Kind: KindView, Scopes: listScopes},
		Command{ID: ReselectLast, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},

		// --- panes and overlays (view) ---
		Command{ID: OpenDetail, Name: "open.detail", Aliases: []string{"detail"}, Usage: ":open.detail", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},
		Command{ID: OpenBrowser, Name: "browse", Aliases: []string{"open.browser", "web"}, Usage: ":browse [PATENT ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenBrowserUSPTO, Name: "browse.uspto", Aliases: []string{"browse-uspto"}, Usage: ":browse.uspto [PATENT ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenBrowserUSPTOGrant, Name: "browse.uspto.grant", Aliases: []string{"browse-grant", "browse.uspto.patent"}, Usage: ":browse.uspto.grant [PATENT ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenBrowserUSPTOPGPub, Name: "browse.uspto.pgpub", Aliases: []string{"browse.uspto.pub", "browse-pgpub", "browse-pub"}, Usage: ":browse.uspto.pgpub [PATENT ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenBrowserGoogle, Name: "browse.google", Aliases: []string{"browse-google"}, Usage: ":browse.google [PATENT ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenMetrics, Name: "metrics", Aliases: []string{"open.metrics", "observability"}, Usage: ":metrics", Kind: KindView},
		Command{ID: OpenCitations, Name: "open.citations", Aliases: []string{"citations"}, Usage: ":open.citations", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeFamily}},
		Command{ID: OpenCitedBy, Name: "open.citedby", Aliases: []string{"citedby"}, Usage: ":open.citedby", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeFamily}},
		Command{ID: OpenParents, Name: "open.parents", Aliases: []string{"parents"}, Usage: ":open.parents", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeFamily}},
		Command{ID: OpenChildren, Name: "open.children", Aliases: []string{"children"}, Usage: ":open.children", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeFamily}},
		Command{ID: OpenFamilyGraph, Name: "open.family", Aliases: []string{"family-tree", "tree"}, Usage: ":open.family [depth] [COUNTRY ...]", Kind: KindView, Scopes: patentScopes},
		Command{ID: FamilyDepthMore, Name: "family.depth.more", Aliases: []string{"family-depth-more"}, Usage: ":family.depth.more", Kind: KindView, Scopes: []Scope{ScopeFamily}},
		Command{ID: FamilyDepthLess, Name: "family.depth.less", Aliases: []string{"family-depth-less"}, Usage: ":family.depth.less", Kind: KindView, Scopes: []Scope{ScopeFamily}},
		Command{ID: FamilyExportMermaid, Name: "export.family.mermaid", Aliases: []string{"export-mermaid", "copy-mermaid", "family.mermaid"}, Usage: ":export.family.mermaid [PATH]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenProjects, Name: "open.projects", Aliases: []string{"projects"}, Usage: ":open.projects", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeCitations, ScopeFamily, ScopeIDS}},
		Command{ID: OpenPatentNote, Name: "open.note", Aliases: []string{"patent-note", "project-note"}, Usage: ":open.note", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenIDS, Name: "open.ids", Aliases: []string{"ids"}, Usage: ":open.ids", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeCitations, ScopeFamily}},
		Command{ID: OpenAssignees, Name: "open.assignees", Aliases: []string{"assignees", "assignee-timeline", "timeline"}, Usage: ":open.assignees", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenAssigneesProject, Name: "open.assignees.project", Aliases: []string{"assignees.project", "project-assignees", "assignee-rollup"}, Usage: ":open.assignees.project", Kind: KindView, Scopes: projectScopes},
		Command{ID: OpenAllAssigneesHistory, Name: "open.all-assignees-history", Aliases: []string{"all-assignees-history", "assignee-stats", "assignee-analytics"}, Usage: ":open.all-assignees-history", Kind: KindView, Scopes: patentScopes},
		Command{ID: PatentExpirationDate, Name: "patent.expiration-date", Aliases: []string{"expiration-date", "expiration", "exp"}, Usage: ":patent.expiration-date [number] [refresh]", Kind: KindView, Scopes: patentScopes},
		Command{ID: OpenClassificationStats, Name: "open.classification-stats", Aliases: []string{"classification-stats", "class-stats"}, Usage: ":open.classification-stats", Kind: KindView, Scopes: []Scope{ScopeDetail}},
		Command{ID: OpenInventors, Name: "open.inventors", Aliases: []string{"inventors"}, Usage: ":open.inventors", Kind: KindView, Scopes: []Scope{ScopeDetail}},
		Command{ID: OpenInventorsDirect, Name: "open.inventors.direct", Aliases: []string{"inventors-direct"}, Usage: ":open.inventors.direct", Kind: KindView, Scopes: []Scope{ScopeDetail}},
		Command{ID: Back, Kind: KindView},
		Command{ID: CloseOverlay, Kind: KindView, Scopes: []Scope{ScopeOverlay}},
		Command{ID: HistoryBack, Name: "history.back", Aliases: []string{"back-history"}, Usage: ":history.back", Kind: KindView},
		Command{ID: HistoryForward, Name: "history.forward", Aliases: []string{"forward-history"}, Usage: ":history.forward", Kind: KindView},
		Command{ID: OpenHistory, Name: "open.history", Aliases: []string{"history", "visits"}, Usage: ":open.history", Kind: KindView},
		Command{ID: OpenActivity, Name: "open.activity", Aliases: []string{"activity", "replay"}, Usage: ":open.activity", Kind: KindView},
		Command{ID: OpenAllNotes, Name: "open.notes", Aliases: []string{"all-notes", "notes"}, Usage: ":open.notes", Kind: KindView},
		Command{ID: OpenOrphans, Name: "orphans", Aliases: []string{"open.orphans", "unassigned"}, Usage: ":orphans", Kind: KindView},
		Command{ID: NotesSortToggle, Kind: KindView, Scopes: []Scope{ScopeNotes}},
		Command{ID: NotesExportMD, Name: "export.notes", Aliases: []string{"export-notes", "notes.export"}, Usage: ":export.notes", Kind: KindView, Scopes: []Scope{ScopeNotes}},
		Command{ID: Refresh, Name: "refresh", Aliases: []string{"reload"}, Usage: ":refresh", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeCitations, ScopeFamily, ScopeProjects, ScopeIDS}},
		Command{ID: OpenSearch, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeCitations, ScopeFamily, ScopeProjects}},
		Command{ID: FullTextSearch, Name: "search.fulltext", Aliases: []string{"fulltext.search", "grep", "search-fulltext"}, Usage: ":search.fulltext [query]", Kind: KindView, Scopes: []Scope{ScopeCatalog}},
		Command{ID: OpenCommand, Kind: KindView},
		Command{ID: JumpMode, Name: "jump", Aliases: []string{"jump-to-field"}, Usage: ":jump", Kind: KindView, Scopes: []Scope{ScopeDetail}},
		Command{ID: SelectVisual, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},
		Command{ID: SelectClear, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},
		Command{ID: SelectAll, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},
		Command{ID: HighlightFamily, Name: "highlight.family", Aliases: []string{"hl-family"}, Usage: ":highlight.family", Kind: KindView, Scopes: []Scope{ScopeCatalog}},
		Command{ID: HighlightCitations, Name: "highlight.citations", Aliases: []string{"hl-citations", "hl-references"}, Usage: ":highlight.citations", Kind: KindView, Scopes: []Scope{ScopeCatalog}},
		Command{ID: RelationFilterCollapse, Name: "relation-filter.collapse", Aliases: []string{"collapse", "fold", "relation_filter.collapse"}, Usage: ":relation-filter.collapse", Kind: KindView, Scopes: []Scope{ScopeCatalog}},
		Command{ID: RelationFilterExpand, Name: "relation-filter.expand", Aliases: []string{"expand", "unfold", "relation_filter.expand"}, Usage: ":relation-filter.expand", Kind: KindView, Scopes: []Scope{ScopeCatalog}},
		Command{ID: ColNext, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeNotes, ScopeOrphans, ScopeMatterOA}},
		Command{ID: ColPrev, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeNotes, ScopeOrphans, ScopeMatterOA}},
		Command{ID: SortApply, Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeNotes, ScopeOrphans, ScopeMatterOA}},
		Command{ID: ProjectActivate, Name: "project.use", Aliases: []string{"use-project"}, Usage: ":project.use [PROJECT]", Kind: KindView, Scopes: projectScopes},
		Command{ID: ProjectClearActive, Name: "project.clear", Aliases: []string{"clear-project"}, Usage: ":project.clear", Kind: KindView, Scopes: projectScopes},

		// --- filtering (view) ---
		Command{ID: Filter, Name: "filter", Aliases: []string{"f", "filter.clear"}, Usage: ":filter <expr>", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFamily}},
		Command{ID: FindOpen, Name: "find", Aliases: []string{"/"}, Usage: ":find", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeCitations, ScopeFullText}},
		Command{ID: FindNext, Name: "find.next", Aliases: []string{"next-match"}, Usage: ":find.next", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: FindPrev, Name: "find.prev", Aliases: []string{"prev-match", "find.previous"}, Usage: ":find.prev", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: IDSEditField, Kind: KindView, Scopes: []Scope{ScopeIDS}},
		Command{ID: IDSToggleFull, Kind: KindView, Scopes: []Scope{ScopeIDS}},
		Command{ID: IDSCycleStatus, Name: "ids.cycle-status", Aliases: []string{"ids.cycle", "cycle-ids"}, Usage: ":ids.cycle-status", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeCitations, ScopeFamily, ScopeIDS}},
		Command{ID: IDSDelete, Kind: KindView, Scopes: []Scope{ScopeIDS}},

		// --- application-wide (view) ---
		Command{ID: Quit, Name: "quit", Aliases: []string{"exit"}, Usage: ":quit", Kind: KindView},
		Command{ID: Help, Name: "help", Aliases: []string{"?"}, Usage: ":help", Kind: KindView},
		Command{ID: OpenFullText, Name: "open.fulltext", Aliases: []string{"fulltext", "claims", "all-claims"}, Usage: ":open.fulltext", Kind: KindView, Scopes: []Scope{ScopeCatalog, ScopeDetail, ScopeMatterOA, ScopeMatterOADetail}},
		Command{ID: AIAnalyze, Name: "ai.analyze", Aliases: []string{"ai", "analyze"}, Usage: ":ai.analyze", Kind: KindView, Scopes: []Scope{ScopeDetail}},
		Command{ID: SettingsAI, Name: "settings.ai", Aliases: []string{"settings", "config"}, Usage: ":settings.ai", Kind: KindView},
		Command{ID: CopyYank, Name: "copy", Aliases: []string{"yank", "clipboard"}, Usage: ":copy", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: CopyYankMeta, Name: "copy.meta", Aliases: []string{"yank-meta", "copy-with-patent"}, Usage: ":copy.meta", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: CopyAll, Name: "copy.all", Aliases: []string{"yank.all", "copy-all", "yank-all"}, Usage: ":copy.all", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: FullTextStageNext, Name: "fulltext.stage.next", Aliases: []string{"stage.next", "next-stage"}, Usage: ":fulltext.stage.next", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: FullTextStagePrev, Name: "fulltext.stage.prev", Aliases: []string{"stage.prev", "prev-stage", "fulltext.stage.previous"}, Usage: ":fulltext.stage.prev", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: FullTextCollapse, Name: "fulltext.collapse", Aliases: []string{"collapse-matches", "fold-matches"}, Usage: ":fulltext.collapse", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: FullTextQuickList, Name: "fulltext.quicklist", Aliases: []string{"quicklist", "match-list", "quickfix"}, Usage: ":fulltext.quicklist", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: NoteAdd, Name: "note.add", Aliases: []string{"add-note", "note"}, Usage: ":note.add", Kind: KindView, Scopes: []Scope{ScopeFullText}},
		Command{ID: NoteOpen, Name: "note.open", Aliases: []string{"show-notes"}, Usage: ":note.open", Kind: KindView, Scopes: []Scope{ScopeFullText}},
	}
}
